version: '2'

services:
  app:
    build:
      context: .
      dockerfile: app.win.Dockerfile
    # You can now specify both a build and an image key if you're using the new file format.
    # docker-compose build will build the image and tag it with the name you've specified,
    # while docker-compose pull will attempt to pull it.
    # https://github.com/docker/compose/releases/tag/1.6.0
    # Workaround for issues:
    # https://github.com/fabric8io/docker-maven-plugin/issues/614
    # https://github.com/fabric8io/docker-maven-plugin/issues/909
    image: custom_app:latest
    container_name: app_container
    environment:
      - MY_SQL_HOST=mysql
      - MY_SQL_PORT=3306
      - MY_SQL_DB_NAME=an_advanced_todo_app_db
      - MY_SQL_USER=user
      - MY_SQL_PASS=password
    networks:
      - network
    depends_on:
      - mysql_container
  mysql:
    build:
      context: .
      dockerfile: mysql.win.Dockerfile
    # You can now specify both a build and an image key if you're using the new file format.
    # docker-compose build will build the image and tag it with the name you've specified,
    # while docker-compose pull will attempt to pull it.
    # https://github.com/docker/compose/releases/tag/1.6.0
    # Workaround for issues:
    # https://github.com/fabric8io/docker-maven-plugin/issues/614
    # https://github.com/fabric8io/docker-maven-plugin/issues/909
    image: custom_mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=passwordR
      - MYSQL_DATABASE=an_advanced_todo_app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - network

networks:
  network:
    name: custom_network
    # https://github.com/docker/for-win/issues/1960?msclkid=5e99a853b5f111ec8b91d8f1ee4d7d73
    # Workaround for issue 'could not find plugin bridge in v1 plugin registry'
    driver: nat