name: An-Advanced-ToDo-App CI/CD in MacOS

on:
  push:
    branches: 
    - master
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    env:
      workdir: .

    name: Build on MacOS
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml', '**/mac-os.yml', '**/tag-release.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven, SonarCloud and Docker
      run: >
        mvn verify -P jacoco,mutation-testing,docker sonar:sonar
        -Dsonar.organization=nikleo-eng-github
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.projectKey=nikleo-eng_an-advanced-todo-app
        -Djava.awt.headless=true
        -Dtestfx.robot=glass
        -Dtestfx.headless=true
        -Dprism.order=sw
        -Dprism.verbose=true
      working-directory: ${{ env.workdir }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Generate JUnit-Jacoco Reports
      run: >
        mvn surefire-report:report-only site:site
        -DgenerateReports=false
      working-directory: ${{ env.workdir }}
      if: ${{ always() }}
    - name: Archive Pitest Report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: pit-report
        path: '**/target/pit-reports'
        if-no-files-found: ignore
    - name: Archive JUnit-Jacoco Reports
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: surefire-report
        path: '**/target/site'
    - name: Upload Final JAR
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: final-jar
        path: '**/target/an-advanced-todo-app-*mac*.jar'
        if-no-files-found: error
    - name: Upload JavaFX Dependencies
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: javafx-dependencies
        path: '**/target/maven-javafx-dependencies/mac'
        if-no-files-found: error
  tag-release:
    if: ${{ success() }}
    needs:
    - build
    uses: ./.github/workflows/tag-release.yml
    with:
      os: mac