name: An-Advanced-ToDo-App CI/CD in MacOS

on:
  push:
    branches: 
    - master
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    env:
      workdir: .

    name: Build on MacOS
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml', '**/mac-os.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven, SonarCloud and Docker
      run: >
        mvn verify -P jacoco,mutation-testing,docker sonar:sonar
        -Dsonar.organization=nikleo-eng-github
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.projectKey=nikleo-eng_an-advanced-todo-app
        -Djava.awt.headless=true
        -Dtestfx.robot=glass
        -Dtestfx.headless=true
        -Dprism.order=sw
        -Dprism.verbose=true
      working-directory: ${{ env.workdir }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Generate JUnit-Jacoco Reports
      run: >
        mvn surefire-report:report-only site:site
        -DgenerateReports=false
      working-directory: ${{ env.workdir }}
      if: ${{ always() }}
    - name: Archive Pitest Report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: pit-report
        path: '**/target/pit-reports'
        if-no-files-found: ignore
    - name: Archive JUnit-Jacoco Reports
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: surefire-report
        path: '**/target/site'
    - name: Upload Final JAR
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: final-jar
        path: '**/target/an-advanced-todo-app-*mac*.jar'
        if-no-files-found: ignore
    - name: Upload JavaFX Dependencies
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: javafx-dependencies
        path: '**/target/maven-javafx-dependencies/mac'
        if-no-files-found: ignore
  tag-release:
    runs-on: ubuntu-latest
    env:
      workdir: .

    name: Tag&Release on Ubuntu
    steps:
    - name: Download Final JAR
      uses: actions/download-artifact@v2
      with:
        name: final-jar
    - name: Download JavaFX Dependencies
      uses: actions/download-artifact@v2
      with:
        name: javafx-dependencies
    - name: Add SHORT_SHA Env Property
      run: echo "short_sha=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      if: ${{ success() }}
    - name: Add APP_VERSION Env Property
      run: >
         echo "app_version=$(mvn help:evaluate -Dexpression=project.version
         -q -DforceStdout)" >> $GITHUB_ENV
      working-directory: ${{ env.workdir }}
      if: ${{ success() }}
    - name: Create Compressed Archive of Final JAR and JavaFX Dependencies
      run: >
         tar -czf an-advanced-todo-app-${{ env.app_version }}-mac.tar.gz
         an-advanced-todo-app-${{ env.app_version }}-mac*.jar
         maven-javafx-dependencies/mac/*.jar
      working-directory: ${{ env.workdir }}/target
      if: ${{ success() }}
    - name: Create Tag and Release
      uses: ncipollo/release-action@v1
      if: ${{ success() }}
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: target/an-advanced-todo-app-${{ env.app_version }}-mac.tar.gz
        artifactContentType: raw
        commit: ${{ env.GITHUB_SHA }}
        draft: false
        generateReleaseNotes: false
        name: v${{ env.app_version }}-${{ env.short_sha }}
        omitBody: true
        omitBodyDuringUpdate: true
        omitDraftDuringUpdate: true
        omitName: false
        omitNameDuringUpdate: false
        omitPrereleaseDuringUpdate: true
        prerelease: false
        removeArtifacts: false
        replacesArtifacts: true
        tag: v${{ env.app_version }}-${{ env.short_sha }}
        token: ${{ secrets.GITHUB_TOKEN }}