name: An-Advanced-ToDo-App CI/CD in Ubuntu

on:
  push:
    branches: 
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: .

    name: Build on Ubuntu
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml', '**/ubuntu.yml', '**/tag-release.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven, SonarCloud and Docker
      run: >
        xvfb-run mvn verify -P jacoco,mutation-testing,docker sonar:sonar
        -Dsonar.organization=nikleo-eng-github
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.projectKey=nikleo-eng_an-advanced-todo-app
      working-directory: ${{ env.workdir }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Generate JUnit-Jacoco Reports
      run: >
        xvfb-run mvn surefire-report:report-only site:site
        -DgenerateReports=false
      working-directory: ${{ env.workdir }}
      if: ${{ always() }}
    - name: Archive Pitest Report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: pit-report
        path: '**/target/pit-reports'
        if-no-files-found: ignore
    - name: Archive JUnit-Jacoco Reports
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: surefire-report
        path: '**/target/site'
    - name: Upload Final JAR
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: final-jar
        path: '**/target/an-advanced-todo-app-*linux*.jar'
        if-no-files-found: error
    - name: Upload JavaFX Dependencies
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: javafx-dependencies
        path: '**/target/maven-javafx-dependencies/linux'
        if-no-files-found: error
    - name: Call Tag&Release Workflow
      uses: ./.github/workflows/tag-release.yml
      if: ${{ success() }}
      with:
        os: linux