name: An-Advanced-ToDo-App CI/CD in Windows

on:
  push:
    branches: 
    - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOCKER_HOST: tcp://localhost:2375
      workdir: .

    name: Build on Windows
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml', '**/windows.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Docker config
      run: >
        sc config docker
        binpath="dockerd.exe --run-service -H tcp://localhost:2375"
    - name: Docker restart
      run: restart-service *docker*
    # Issue with Windows DPI Scaling and JavaFX
    # https://stackoverflow.com/questions/67264613
    # https://github.com/TestFX/TestFX/issues/711
    # https://github.com/TestFX/TestFX/issues/704
    # https://github.com/TestFX/TestFX/issues/226
    # https://stackoverflow.com/questions/45754473
    # https://superuser.com/questions/988379
    - name: Build with Maven and SonarCloud
      run: >
        mvn verify -P jacoco,mutation-testing sonar:sonar
        "-Dsonar.organization=nikleo-eng-github"
        "-Dsonar.host.url=https://sonarcloud.io"
        "-Dsonar.projectKey=nikleo-eng_an-advanced-todo-app"
        "-Dtestfx.robot=awt"
        "-Dtestfx.awt.scale=true"
        "-Dglass.win.uiScale=50%"
      working-directory: ${{ env.workdir }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Generate JUnit-Jacoco Reports
      run: >
        mvn surefire-report:report-only site:site
        "-DgenerateReports=false"
      working-directory: ${{ env.workdir }}
      if: ${{ always() }}
    - name: Archive Pitest Report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: pit-report
        path: '**/target/pit-reports'
        if-no-files-found: ignore
    - name: Archive JUnit-Jacoco Reports
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: surefire-report
        path: '**/target/site'
    - name: Archive Final JARs
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: final-jars
        path: '**/target/an-advanced-todo-app-*.jar'
        if-no-files-found: ignore
    - name: Archive JavaFX Dependencies
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: javafx-dependencies
        path: '**/target/maven-javafx-dependencies/windows'
        if-no-files-found: ignore